on: push
name: Slack Notification Demo
jobs:
    build:
        
        
        runs-on: ubuntu-latest
        env: 
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
        steps:
        
        - name: Run tests
          run: ls
        
        - uses: act10ns/slack@v1
          with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            channel: '#random'
        if: always()
