on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
