on: push
name: Slack Notification Demo
jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
        - name: Report Status
          if: always()
          uses: ravsamhq/notify-slack-action@master
          with:
            status: ${{ job.status }}
            notify_when: 'failure'
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            
        - name: Report Success
          if: always()
          uses: ravsamhq/notify-slack-action@master
          with:
            status: ${{ job.status }}
            notify_when: 'success'
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
